from __future__ import annotations

from ..domain.types import EmbodiedResourceSummary

CATALOG: tuple[EmbodiedResourceSummary, ...] = (
    {
        "id": "resource_grounding_breath_3",
        "title": "Three-minute grounding breath",
        "provider": "circulatio",
        "url": "circulatio://resources/grounding-breath-3",
        "resourceType": "breath_container",
        "durationMinutes": 3,
        "modality": "breath",
        "activationBand": "overwhelming",
        "contraindications": ["stop_if_dizziness_or_distress_increases"],
        "tags": ["grounding", "brief", "no_interpretation"],
        "followUpQuestion": "What changed in your body after three quieter breaths?",
        "curationSource": "core_catalog_v1",
        "reviewedAt": "2026-04-21T00:00:00Z",
    },
    {
        "id": "resource_body_scan_5",
        "title": "Five-minute body scan",
        "provider": "circulatio",
        "url": "circulatio://resources/body-scan-5",
        "resourceType": "audio",
        "durationMinutes": 5,
        "modality": "body_scan",
        "activationBand": "high",
        "contraindications": ["skip_if_internal_attention_feels_overwhelming"],
        "tags": ["somatic", "grounding", "paced"],
        "followUpQuestion": "What part of the body asked for the most room?",
        "curationSource": "core_catalog_v1",
        "reviewedAt": "2026-04-21T00:00:00Z",
    },
    {
        "id": "resource_somatic_tracking_note",
        "title": "Somatic tracking note",
        "provider": "circulatio",
        "url": "circulatio://resources/somatic-tracking-note",
        "resourceType": "interactive_card",
        "durationMinutes": 4,
        "modality": "somatic_tracking",
        "activationBand": "moderate",
        "contraindications": ["skip_if_tracking_turns_into_forcing"],
        "tags": ["soma", "tracking", "lightweight"],
        "followUpQuestion": "What changed before you explained it?",
        "curationSource": "core_catalog_v1",
        "reviewedAt": "2026-04-21T00:00:00Z",
    },
    {
        "id": "resource_journaling_bridge_5",
        "title": "Five-minute journaling bridge",
        "provider": "circulatio",
        "url": "circulatio://resources/journaling-bridge-5",
        "resourceType": "text",
        "durationMinutes": 5,
        "modality": "journaling",
        "activationBand": "low",
        "contraindications": [],
        "tags": ["journaling", "bridge", "lightweight"],
        "followUpQuestion": "What feels a little more workable after writing it plainly?",
        "curationSource": "core_catalog_v1",
        "reviewedAt": "2026-04-21T00:00:00Z",
    },
)
